### ISSUE TITLE
Track `name of month`, `name of day` and `hour of day`

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/spoor-consumer#102]
Example questions: 
"Do people opt in more in the mornings or in the afternoons?"
"What's the best time to email ft.com users, inviting them to opt into nextFT?"
"Is the best time different for different devices? What about other metrics?"

To answer that, it'd be good to be able to 

1. count all users who opted in for the last (say) 3 months, 
2. group the counts by the hour of day.

So regardless of the date, all of the 6am opt-ins would be in one group, all the 7am opt-ins in another, so on and so forth. 

And while we are at it, the same would be useful for name of day and name of month.

**Comment by commuterjoy** [comment]
https://github.com/Financial-Times/spoor-enrichment/issues/213 - some mention of something similar here.

**Comment by adambraimbridge** [comment]
See: https://github.com/Financial-Times/spoor-enrichment/pull/389 and https://spoor-docs.herokuapp.com/annotations#localtime
