### ISSUE TITLE
Enable segmentID in spoor-consumer

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/spoor-consumer#123]
![image](https://cloud.githubusercontent.com/assets/224547/17856046/8e829e32-6873-11e6-982a-15dab4a0cf0f.png)

**Comment by ironsidevsquincy** [comment]
Segment ID should be captured now

https://github.com/Financial-Times/ft.com-cdn/pull/191
https://github.com/Financial-Times/n-ui/pull/358

**Comment by adambraimbridge** [comment]
Outstanding, thanks @ironsidevsquincy

**Comment by adambraimbridge** [comment]
Currently blocked by https://github.com/Financial-Times/n-webpack/pull/24

**Comment by adambraimbridge** [comment]
![image](https://cloud.githubusercontent.com/assets/224547/17965542/0426de26-6ab5-11e6-8f7f-8fc5cc8639d0.png)
