### ISSUE TITLE
oGridLayout standardisation

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/spoor-consumer#67]
- map `default` and any string containing `XS` to `XS`
- map any string containing `XL` to `XL`

not sure if this is a good solution? What if home page really want stats on XXL. Cross that bridge as and when?

**Comment by adgad** [comment]
It makes _sense_ - that's pretty much what we did on all our homepage dashboards - but I think it might be a little confusing. What about calling it something like XL+ and XS- (so it's obvious it's not the same as the actual breakpoint?)

**Comment by wheresrhys** [comment]
trouble is that then it'd still fail to be able to compare like with like between a page that does have the extra layouts and one that doesn't. Not sure which is the lesser of two evils. We could just do something where o-tracking sends additional property of page width rounded to the nearest Xpx, where X is the gap between standard oGridLayouts (which I *think* is a fixed value (not that I agree with it being one))

It could all be done in keen-query/beacon by creating a `->normalizeOGrid()` method, but I kinda like the idea of standardising the data on the way in

**Comment by wheresrhys** [comment]
yes, I think that's best
